CREATE TABLE users (user_id INTEGER AUTO_INCREMENT PRIMARY KEY, username STRING NOT NULL, age INTEGER, email STRING);

CREATE TABLE team (user_id INTEGER AUTO_INCREMENT PRIMARY KEY, username STRING NOT NULL, age INTEGER, email STRING);